name: Publish Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build Docker Images for Separate Repositories
      - name: Build Docker Image Client
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kid-client:latest ./client

      - name: Build Docker Image Dashboard
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kid-dashboard:latest ./dashboard

      - name: Build Docker Image Server
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kid-server:latest ./server

      - name: Build Docker Image Backup Service
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kid-backup-service:latest ./backup-service

      # Push Docker Images to Separate Repositories
      - name: Push Docker Image Client
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kid-client:latest

      - name: Push Docker Image Dashboard
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kid-dashboard:latest

      - name: Push Docker Image Server
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kid-server:latest

      - name: Push Docker Image Backup Service
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kid-backup-service:latest